import type { LiquidGlassTheme } from './types';

const themeToVarMap: Record<keyof LiquidGlassTheme, string> = {
  blur: '--lg-blur',
  bgOpacity: '--lg-bg-opacity',
  borderOpacity: '--lg-border-opacity',
  surface: '--lg-surface',
  border: '--lg-border',
  reflection: '--lg-reflection',
  easing: '--lg-easing',
  transitionDuration: '--lg-transition-duration',
  shadowSoft: '--lg-shadow-soft',
  shadowSharp: '--lg-shadow-sharp',
  colorPrimary: '--lg-color-primary',
  colorPrimaryDark: '--lg-color-primary-dark',
  colorPrimaryLight: '--lg-color-primary-light',
  colorError: '--lg-color-error',
  colorErrorDark: '--lg-color-error-dark',
  colorErrorLight: '--lg-color-error-light',
  colorErrorBg: '--lg-color-error-bg',
  colorErrorText: '--lg-color-error-text',
  colorWarningBg: '--lg-color-warning-bg',
  colorWarningText: '--lg-color-warning-text',
  colorInfoBg: '--lg-color-info-bg',
  colorInfoText: '--lg-color-info-text',
  colorSuccessBg: '--lg-color-success-bg',
  colorSuccessText: '--lg-color-success-text',
  colorTextPrimary: '--lg-color-text-primary',
  colorTextSecondary: '--lg-color-text-secondary',
  colorTextDisabled: '--lg-color-text-disabled',
  colorDivider: '--lg-color-divider',
  colorActionHover: '--lg-color-action-hover',
  colorBackground: '--lg-color-background',
  colorPaper: '--lg-color-paper',
  colorChipFilled: '--lg-color-chip-filled',
  colorTextOnSurface: '--lg-color-text-on-surface',
  colorTextOnSurfaceSecondary: '--lg-color-text-on-surface-secondary',
  bgFallback: '--lg-bg-fallback',
  fontFamily: '--lg-font-family',
  radiusSm: '--lg-radius-sm',
  radiusMd: '--lg-radius-md',
  radiusLg: '--lg-radius-lg',
  shadow1: '--lg-shadow-1',
  shadow2: '--lg-shadow-2',
  shadow4: '--lg-shadow-4',
  transitionFast: '--lg-transition-fast',
  transitionNormal: '--lg-transition-normal',
};

export { themeToVarMap };
